# Generated by Django 2.2.2 on 2020-06-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='TemperatureReadings',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False)),
                ('reading', models.FloatField(default=0.0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
            ],
            options={
                'db_table': 'temperature_readings',
            },
        ),
        migrations.CreateModel(
            name='HumidityReadings',
            fields=[
                ('hid', models.BigAutoField(primary_key=True, serialize=False)),
                ('reading', models.FloatField(default=0.0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
            ],
            options={
                'db_table': 'humidity_readings',
            },
        ),
    ]
