# Generated by Django 2.2.2 on 2020-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreadings',
            name='ends_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='humidityreadings',
            name='starts_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temperaturereadings',
            name='ends_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='temperaturereadings',
            name='starts_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
